server:
  port: 6666


spring:
  rabbitmq:
    host: 192.168.170.128
    port: 5672
    username: soda
    password: soda
    virtual-host: soda4
    connection-timeout: 10s
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 20
        retry:
          enabled: false